package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HbcategoryscalinggroupsId generated by hbm2java
 */
@Embeddable
public class HbcategoryscalinggroupsId implements java.io.Serializable {

	private BigDecimal sgpHbid;
	private BigDecimal catHbid;

	public HbcategoryscalinggroupsId() {
	}

	public HbcategoryscalinggroupsId(BigDecimal sgpHbid, BigDecimal catHbid) {
		this.sgpHbid = sgpHbid;
		this.catHbid = catHbid;
	}

	@Column(name = "SGP_HBID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSgpHbid() {
		return this.sgpHbid;
	}

	public void setSgpHbid(BigDecimal sgpHbid) {
		this.sgpHbid = sgpHbid;
	}

	@Column(name = "CAT_HBID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCatHbid() {
		return this.catHbid;
	}

	public void setCatHbid(BigDecimal catHbid) {
		this.catHbid = catHbid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HbcategoryscalinggroupsId))
			return false;
		HbcategoryscalinggroupsId castOther = (HbcategoryscalinggroupsId) other;

		return ((this.getSgpHbid() == castOther.getSgpHbid()) || (this.getSgpHbid() != null
				&& castOther.getSgpHbid() != null && this.getSgpHbid().equals(castOther.getSgpHbid())))
				&& ((this.getCatHbid() == castOther.getCatHbid()) || (this.getCatHbid() != null
						&& castOther.getCatHbid() != null && this.getCatHbid().equals(castOther.getCatHbid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSgpHbid() == null ? 0 : this.getSgpHbid().hashCode());
		result = 37 * result + (getCatHbid() == null ? 0 : this.getCatHbid().hashCode());
		return result;
	}

}
