/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;
import org.sede.servicio.qys.ConfigQys;

/**
 * Hbrequestpriorities generated by hbm2java
 */
@XmlRootElement(name="priority")
@Entity
@Table(name = "HBREQUESTPRIORITIES", schema = ConfigQys.ESQUEMA)
public class Hbrequestpriorities implements java.io.Serializable {

	private BigDecimal rptHbid;
	private String rptName;
	private BigDecimal rptPriority;
	private BigDecimal rptHbversion;
	private BigDecimal rptDefault;
	
	public Hbrequestpriorities() {
	}

	public Hbrequestpriorities(BigDecimal rptHbid, String rptName, BigDecimal rptPriority, BigDecimal rptHbversion,
			BigDecimal rptDefault) {
		this.rptHbid = rptHbid;
		this.rptName = rptName;
		this.rptPriority = rptPriority;
		this.rptHbversion = rptHbversion;
		this.rptDefault = rptDefault;
	}

	@Id
	@Column(name = "RPT_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRptHbid() {
		return this.rptHbid;
	}

	public void setRptHbid(BigDecimal rptHbid) {
		this.rptHbid = rptHbid;
	}

	@Column(name = "RPT_NAME", nullable = false, length = 30)
	public String getRptName() {
		return this.rptName;
	}

	public void setRptName(String rptName) {
		this.rptName = rptName;
	}

	@Column(name = "RPT_PRIORITY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRptPriority() {
		return this.rptPriority;
	}

	public void setRptPriority(BigDecimal rptPriority) {
		this.rptPriority = rptPriority;
	}

	@Column(name = "RPT_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRptHbversion() {
		return this.rptHbversion;
	}

	public void setRptHbversion(BigDecimal rptHbversion) {
		this.rptHbversion = rptHbversion;
	}

	@Column(name = "RPT_DEFAULT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRptDefault() {
		return this.rptDefault;
	}

	public void setRptDefault(BigDecimal rptDefault) {
		this.rptDefault = rptDefault;
	}


}
