package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.BatchSize;
import org.sede.core.anotaciones.Interno;
import org.sede.servicio.qys.ConfigQys;

/**
 * Hbrequestactions generated by hbm2java
 */
@XmlRootElement(name="request-action")
@Entity
@Table(name = "HBREQUESTACTIONS", schema = ConfigQys.ESQUEMA)
@BatchSize(size = 50)
public class Hbrequestactions implements java.io.Serializable {

	private BigDecimal rqaHbid;
	private BigDecimal rqaHbversion;
	private String description;
	private Date creation_date;
	private Date rqaRequestactiondatetime;
	private BigDecimal rqaElapsedseconds;
	private BigDecimal usrHbidAgent;
	@Interno
	private Hbrequests hbrequests;
	
	private BigDecimal type;
	
	private String type_name;
	
	@Interno
	private Hbrequestactiontypes ratHbidType;
	
	
	private BigDecimal rssHbidSubstate;
	private BigDecimal rssSlaStop;
	private String operador;

	public Hbrequestactions() {
	}

	public Hbrequestactions(BigDecimal rqaHbid, BigDecimal rqaHbversion, String rqaDescription,
			Date rqaCreationdatetime, Date rqaRequestactiondatetime, BigDecimal rqaElapsedseconds,
			BigDecimal usrHbidAgent, Hbrequests hbrequests, BigDecimal rssHbidSubstate, BigDecimal rssSlaStop) {
		this.rqaHbid = rqaHbid;
		this.rqaHbversion = rqaHbversion;
		this.description = rqaDescription;
		this.creation_date = rqaCreationdatetime;
		this.rqaRequestactiondatetime = rqaRequestactiondatetime;
		this.rqaElapsedseconds = rqaElapsedseconds;
		this.usrHbidAgent = usrHbidAgent;
		this.hbrequests = hbrequests;
		this.rssHbidSubstate = rssHbidSubstate;
		this.rssSlaStop = rssSlaStop;
	}

	public Hbrequestactions(BigDecimal rqaHbid, BigDecimal rqaHbversion, String rqaDescription,
			Date rqaCreationdatetime, Date rqaRequestactiondatetime, BigDecimal rqaElapsedseconds,
			BigDecimal usrHbidAgent, Hbrequests hbrequests, Hbrequestactiontypes ratHbidType, BigDecimal rssHbidSubstate,
			BigDecimal rssSlaStop, String operador) {
		this.rqaHbid = rqaHbid;
		this.rqaHbversion = rqaHbversion;
		this.description = rqaDescription;
		this.creation_date = rqaCreationdatetime;
		this.rqaRequestactiondatetime = rqaRequestactiondatetime;
		this.rqaElapsedseconds = rqaElapsedseconds;
		this.usrHbidAgent = usrHbidAgent;
		this.hbrequests = hbrequests;
		this.ratHbidType = ratHbidType;
		this.rssHbidSubstate = rssHbidSubstate;
		this.rssSlaStop = rssSlaStop;
		this.operador = operador;
	}

	@Id
	@Column(name = "RQA_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqaHbid() {
		return this.rqaHbid;
	}

	public void setRqaHbid(BigDecimal rqaHbid) {
		this.rqaHbid = rqaHbid;
	}

	@Column(name = "RQA_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqaHbversion() {
		return this.rqaHbversion;
	}

	public void setRqaHbversion(BigDecimal rqaHbversion) {
		this.rqaHbversion = rqaHbversion;
	}

	@Column(name = "RQA_DESCRIPTION", nullable = false, length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String rqaDescription) {
		this.description = rqaDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RQA_CREATIONDATETIME", nullable = false, length = 7)
	public Date getCreation_date() {
		return this.creation_date;
	}

	public void setCreation_date(Date rqaCreationdatetime) {
		this.creation_date = rqaCreationdatetime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RQA_REQUESTACTIONDATETIME", nullable = false, length = 7)
	public Date getRqaRequestactiondatetime() {
		return this.rqaRequestactiondatetime;
	}

	public void setRqaRequestactiondatetime(Date rqaRequestactiondatetime) {
		this.rqaRequestactiondatetime = rqaRequestactiondatetime;
	}

	@Column(name = "RQA_ELAPSEDSECONDS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqaElapsedseconds() {
		return this.rqaElapsedseconds;
	}

	public void setRqaElapsedseconds(BigDecimal rqaElapsedseconds) {
		this.rqaElapsedseconds = rqaElapsedseconds;
	}

	@Column(name = "USR_HBID_AGENT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbidAgent() {
		return this.usrHbidAgent;
	}

	public void setUsrHbidAgent(BigDecimal usrHbidAgent) {
		this.usrHbidAgent = usrHbidAgent;
	}

		@Column(name = "RSS_HBID_SUBSTATE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRssHbidSubstate() {
		return this.rssHbidSubstate;
	}

	public void setRssHbidSubstate(BigDecimal rssHbidSubstate) {
		this.rssHbidSubstate = rssHbidSubstate;
	}

	@Column(name = "RSS_SLA_STOP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRssSlaStop() {
		return this.rssSlaStop;
	}

	public void setRssSlaStop(BigDecimal rssSlaStop) {
		this.rssSlaStop = rssSlaStop;
	}

	@Transient
	public String getType_name() {
		return this.ratHbidType.getRatName();
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RAT_HBID_TYPE")
	public Hbrequestactiontypes getRatHbidType() {
		return ratHbidType;
	}

	public void setRatHbidType(Hbrequestactiontypes ratHbidType) {
		this.ratHbidType = ratHbidType;
	}

	@Transient
	public BigDecimal getType() {
		return this.ratHbidType.getRatHbid();
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	@Column(name = "OPERADOR", length = 200)
	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RQT_HBID_REQUEST", nullable = false, insertable = false, updatable = false)
	public Hbrequests getHbrequests() {
		return this.hbrequests;
	}

	public void setHbrequests(Hbrequests hbrequests) {
		this.hbrequests = hbrequests;
	}

}
