/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.servicio.qys.ConfigQys;

/**
 * Hbrequesttoken generated by hbm2java
 */
@XmlRootElement(name="token")
@Entity
@Table(name = "HBREQUESTTOKEN", schema = ConfigQys.ESQUEMA)
public class Hbrequesttoken implements java.io.Serializable {

	private HbrequesttokenId id;
	private Hbrequests hbrequests;
	private String token;

	public Hbrequesttoken() {
	}

	public Hbrequesttoken(HbrequesttokenId id, Hbrequests hbrequests) {
		this.id = id;
		this.hbrequests = hbrequests;
	}

	public Hbrequesttoken(HbrequesttokenId id, Hbrequests hbrequests, String token) {
		this.id = id;
		this.hbrequests = hbrequests;
		this.token = token;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rqtHbid", column = @Column(name = "RQT_HBID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "rqaHbid", column = @Column(name = "RQA_HBID", nullable = false, precision = 22, scale = 0)) })
	public HbrequesttokenId getId() {
		return this.id;
	}

	public void setId(HbrequesttokenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RQT_HBID", nullable = false, insertable = false, updatable = false)
	public Hbrequests getHbrequests() {
		return this.hbrequests;
	}

	public void setHbrequests(Hbrequests hbrequests) {
		this.hbrequests = hbrequests;
	}

	@Column(name = "TOKEN", length = 100)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
