/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.servicio.qys.ConfigQys;

/**
 * Hbrequesttypes generated by hbm2java
 */
@XmlRootElement(name="type")
@Entity
@Table(name = "HBREQUESTTYPES", schema = ConfigQys.ESQUEMA)
public class Hbrequesttypes implements java.io.Serializable {

	private BigDecimal rtyHbid;
	private String rtyName;
	private BigDecimal rtyHbversion;
	private BigDecimal rtyDefault;
	private BigDecimal rtyTicker;

	public Hbrequesttypes() {
	}

	public Hbrequesttypes(BigDecimal rtyHbid, String rtyName, BigDecimal rtyHbversion, BigDecimal rtyDefault,
			BigDecimal rtyTicker) {
		this.rtyHbid = rtyHbid;
		this.rtyName = rtyName;
		this.rtyHbversion = rtyHbversion;
		this.rtyDefault = rtyDefault;
		this.rtyTicker = rtyTicker;
	}

	@Id

	@Column(name = "RTY_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRtyHbid() {
		return this.rtyHbid;
	}

	public void setRtyHbid(BigDecimal rtyHbid) {
		this.rtyHbid = rtyHbid;
	}

	@Column(name = "RTY_NAME", nullable = false, length = 30)
	public String getRtyName() {
		return this.rtyName;
	}

	public void setRtyName(String rtyName) {
		this.rtyName = rtyName;
	}

	@Column(name = "RTY_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRtyHbversion() {
		return this.rtyHbversion;
	}

	public void setRtyHbversion(BigDecimal rtyHbversion) {
		this.rtyHbversion = rtyHbversion;
	}

	@Column(name = "RTY_DEFAULT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRtyDefault() {
		return this.rtyDefault;
	}

	public void setRtyDefault(BigDecimal rtyDefault) {
		this.rtyDefault = rtyDefault;
	}

	@Column(name = "RTY_TICKER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRtyTicker() {
		return this.rtyTicker;
	}

	public void setRtyTicker(BigDecimal rtyTicker) {
		this.rtyTicker = rtyTicker;
	}

}
