package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.sede.core.anotaciones.Context;
import org.sede.core.anotaciones.GeoJson;
import org.sede.core.anotaciones.InList;
import org.sede.core.anotaciones.Interno;
import org.sede.core.anotaciones.PathId;
import org.sede.core.anotaciones.Permisos;
import org.sede.core.anotaciones.Rdf;
import org.sede.core.anotaciones.RequiredSinValidacion;
import org.sede.core.anotaciones.ResultsOnly;
import org.sede.core.anotaciones.SoloEnEstaEntidad;
import org.sede.core.dao.EntidadBase;
import org.sede.core.geo.Geometria;
import org.sede.core.geo.Punto;
import org.sede.core.rest.CheckeoParametros;
import org.sede.core.utils.Funciones;
//import org.sede.servicio.asociacion.entity.Categoria;
//import org.sede.servicio.callejero.entity.Portalero;
import org.sede.servicio.qys.QysController;

/**
 * Hbrequests generated by hbm2java
 */
@XmlRootElement(name="request")
@ResultsOnly(xmlroot="service_requests")
@Rdf(contexto=Context.OPEN311, propiedad="ServiceRequest")
@GeoJson(title = "Quejas y sugerencias", description = "Localización", icon = "queja", link = "/sede/servicio/quejas-sugerencias/")
@PathId("/" + QysController.MAPPING)
@Entity
@Table(name = "HBREQUESTS", schema = "TICKETING")
public class Hbrequests extends EntidadBase implements java.io.Serializable {

	private BigDecimal service_request_id;
	
	@InList({"open", "closed"})
	private String status;
	
	private BigDecimal service_code;
	
	private String service_name;
	
	@Permisos(Permisos.DET)
	private String status_admin;
	
	@Permisos(Permisos.DET)
	private Hbcategorylevels hbcategories;
	
	private String title;
	
	private String description;
	
	private String service_notice;
	
	private String addressString;
	
	private Integer addressId;
	
	private Date requested_datetime;
	
	// es el campo rqtClosedatetime
	private Date updated_datetime;
	
	private String rqtGeolocation;
	
	@Interno
	private BigDecimal rqtHbid;
	
	@Permisos(Permisos.DET)
	private HbEntidadesexternas hbEntidadesexternas;
	@Permisos(Permisos.DET)
	private Hbrequestpriorities hbrequestpriorities;
	@Permisos(Permisos.DET)
	private Hbrequeststates hbrequeststates;
	@Permisos(Permisos.DET)
	private Hbscalinggroups hbscalinggroups;
	@Permisos(Permisos.DET)
	private BigDecimal rqtHbversion;
	@Permisos(Permisos.DET)
	private BigDecimal usrHbidRequester;
	@Permisos(Permisos.DET)
	private BigDecimal usrHbidIntroducer;
	@Permisos(Permisos.DET)
	private BigDecimal usrHbidManager;
	@Permisos(Permisos.DET)
	private BigDecimal origin;
	
	@Permisos(Permisos.DET)
//	@SoloEnEstaEntidad
	@BatchSize(size = 50)
	@OrderBy("rqaCreationdatetime desc")
	private List<Hbrequestactions> actions = new ArrayList<Hbrequestactions>();
	
	@Permisos(Permisos.DET)
	@SoloEnEstaEntidad
	@BatchSize(size = 50)
	private List<Hbrequestloadfiles> attachments = new ArrayList<Hbrequestloadfiles>();
	
	@Permisos(Permisos.DET)
	private Hbrequesttypes type;
	
	@Permisos(Permisos.DET)
	private String rqtCreationdescription;
	@Permisos(Permisos.DET)
	private Date rqtRequestdatetime;
	@Permisos(Permisos.DET)
	private Date rqtRequestdate;
	
//	@Interno
//	private Portalero portal;
	
	@Interno
	private BigDecimal x;

	@Interno
	private BigDecimal y;
	
	@Rdf(contexto = Context.GEO, propiedad = "geometry")
	@RequiredSinValidacion
	private Punto geometry;
	
	@Permisos(Permisos.DET)
	private Date rqtExpectedresolutiondatetime;
	@Permisos(Permisos.DET)
	private Date rqtClosedate;
	@Permisos(Permisos.DET)
	private BigDecimal macHbidMachine;
	@Permisos(Permisos.DET)
	private BigDecimal numrefcasd;
	@Permisos(Permisos.DET)
	private BigDecimal idcasd;
	@Permisos(Permisos.DET)
	private BigDecimal rqtRequesthour;
	@Permisos(Permisos.DET)
	private Date rqtResolveddatatime;
	private BigDecimal rqtParentId;
	@Permisos(Permisos.DET)
	private String rqtPublic;
	@Permisos(Permisos.DET)
	private String validated;
	
	@Permisos(Permisos.DET)
	private Date rqtGestordate;
	@Permisos(Permisos.DET)
	private Date rqtExternodate;
	@Permisos(Permisos.DET)
	private String operador;
	@Permisos(Permisos.DET)
	private String answerRequested;
	@Permisos(Permisos.DET)
	private Date rqtInspectordate;
	
	@Permisos(Permisos.ZONAINSPECCION)
	private String interno_code;
	
	@Permisos(Permisos.DET)
	private BigDecimal rqtZonainspeccionid;
	@Permisos(Permisos.DET)
	private BigDecimal internalStatus;
	private String notes;
	@Permisos(Permisos.DET)
	private BigDecimal idCita;
	
	@Permisos(Permisos.DET)
	private String token;
	@Permisos(Permisos.DET)
	private BigDecimal userId;
	
	
	@Permisos(Permisos.DET)
	private String firstName;
	@Permisos(Permisos.DET)
	private String email;
	@Permisos(Permisos.DET)
	private String phone;
	@Permisos(Permisos.DET)
	private String userAddress;
	
	public CategoriaSIP catSip;
	

	public Hbrequests() {
	}

	public Hbrequests(BigDecimal rqtHbid, BigDecimal rqtHbversion, Date requested_datetime,
			String rqtCreationdescription, BigDecimal numrefcasd, BigDecimal idcasd, BigDecimal rqtRequesthour,
			String rqtPublic, String validated) {
		this.rqtHbid = rqtHbid;
		this.rqtHbversion = rqtHbversion;
		this.requested_datetime = requested_datetime;
		this.rqtCreationdescription = rqtCreationdescription;
		this.numrefcasd = numrefcasd;
		this.idcasd = idcasd;
		this.rqtRequesthour = rqtRequesthour;
		this.rqtPublic = rqtPublic;
		this.validated = validated;
	}

	public Hbrequests(BigDecimal rqtHbid, Hbcategorylevels hbcategories, HbEntidadesexternas hbEntidadesexternas,
			Hbrequestpriorities hbrequestpriorities, Hbrequeststates hbrequeststates, Hbscalinggroups hbscalinggroups,
			BigDecimal rqtHbversion, BigDecimal usrHbidRequester, BigDecimal usrHbidIntroducer,
			BigDecimal usrHbidManager, BigDecimal origin, Hbrequesttypes type, Date requested_datetime,
			String rqtCreationdescription, Date rqtRequestdatetime, Date rqtRequestdate, BigDecimal service_request_id,
			Date rqtExpectedresolutiondatetime, Date updated_datetime, Date rqtClosedate, BigDecimal macHbidMachine,
			BigDecimal numrefcasd, BigDecimal idcasd, BigDecimal rqtRequesthour, Date rqtResolveddatatime,
			BigDecimal rqtParentId, String rqtPublic, String validated, String rqtGeolocation,
			Date rqtGestordate, Date rqtExternodate, String operador, String answerRequested, Date rqtInspectordate,
			String internoCode, BigDecimal rqtZonainspeccionid, BigDecimal internalStatus, String notes,
			BigDecimal idCita, String token, BigDecimal userId, String description, String title,
			String firstName, String email, String phone, String userAddress, String addressString,
			Integer addressId, String serviceNotice, List<Hbrequestactions> actions) {
		this.rqtHbid = rqtHbid;
		this.hbcategories = hbcategories;
		this.hbEntidadesexternas = hbEntidadesexternas;
		this.hbrequestpriorities = hbrequestpriorities;
		this.hbrequeststates = hbrequeststates;
		this.hbscalinggroups = hbscalinggroups;
		this.rqtHbversion = rqtHbversion;
		this.usrHbidRequester = usrHbidRequester;
		this.usrHbidIntroducer = usrHbidIntroducer;
		this.usrHbidManager = usrHbidManager;
		this.origin = origin;
		this.type = type;
		this.requested_datetime = requested_datetime;
		this.rqtCreationdescription = rqtCreationdescription;
		this.rqtRequestdatetime = rqtRequestdatetime;
		this.rqtRequestdate = rqtRequestdate;
		this.service_request_id = service_request_id;
		this.rqtExpectedresolutiondatetime = rqtExpectedresolutiondatetime;
		this.updated_datetime = updated_datetime;
		this.rqtClosedate = rqtClosedate;
		this.macHbidMachine = macHbidMachine;
		this.numrefcasd = numrefcasd;
		this.idcasd = idcasd;
		this.rqtRequesthour = rqtRequesthour;
		this.rqtResolveddatatime = rqtResolveddatatime;
		this.rqtParentId = rqtParentId;
		this.rqtPublic = rqtPublic;
		this.validated = validated;
		this.rqtGeolocation = rqtGeolocation;
		this.rqtGestordate = rqtGestordate;
		this.rqtExternodate = rqtExternodate;
		this.operador = operador;
		this.answerRequested = answerRequested;
		this.rqtInspectordate = rqtInspectordate;
		this.interno_code = internoCode;
		this.rqtZonainspeccionid = rqtZonainspeccionid;
		this.internalStatus = internalStatus;
		this.notes = notes;
		this.idCita = idCita;
		this.token = token;
		this.userId = userId;
		this.description = description;
		this.title = title;
		this.firstName = firstName;
		this.email = email;
		this.phone = phone;
		this.userAddress = userAddress;
		this.addressString = addressString;
		this.addressId = addressId;
		this.service_notice = serviceNotice;
		this.actions = actions;
	}

	@Id
	@Column(name = "RQT_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqtHbid() {
		return this.rqtHbid;
	}

	public void setRqtHbid(BigDecimal rqtHbid) {
		this.rqtHbid = rqtHbid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CAT_HBID")
	public Hbcategorylevels getHbcategories() {
		return this.hbcategories;
	}

	public void setHbcategories(Hbcategorylevels hbcategories) {
		this.hbcategories = hbcategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RQT_EXTERNOID")
	public HbEntidadesexternas getHbEntidadesexternas() {
		return this.hbEntidadesexternas;
	}

	public void setHbEntidadesexternas(HbEntidadesexternas hbEntidadesexternas) {
		this.hbEntidadesexternas = hbEntidadesexternas;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RPT_HBID")
	public Hbrequestpriorities getHbrequestpriorities() {
		return this.hbrequestpriorities;
	}

	public void setHbrequestpriorities(Hbrequestpriorities hbrequestpriorities) {
		this.hbrequestpriorities = hbrequestpriorities;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RST_ID")
	public Hbrequeststates getHbrequeststates() {
		return this.hbrequeststates;
	}

	public void setHbrequeststates(Hbrequeststates hbrequeststates) {
		this.hbrequeststates = hbrequeststates;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SGP_HBID")
	public Hbscalinggroups getHbscalinggroups() {
		return this.hbscalinggroups;
	}

	public void setHbscalinggroups(Hbscalinggroups hbscalinggroups) {
		this.hbscalinggroups = hbscalinggroups;
	}

	@Column(name = "RQT_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqtHbversion() {
		return this.rqtHbversion;
	}

	public void setRqtHbversion(BigDecimal rqtHbversion) {
		this.rqtHbversion = rqtHbversion;
	}

	@Column(name = "USR_HBID_REQUESTER", precision = 22, scale = 0)
	public BigDecimal getUsrHbidRequester() {
		return this.usrHbidRequester;
	}

	public void setUsrHbidRequester(BigDecimal usrHbidRequester) {
		this.usrHbidRequester = usrHbidRequester;
	}

	@Column(name = "USR_HBID_INTRODUCER", precision = 22, scale = 0)
	public BigDecimal getUsrHbidIntroducer() {
		return this.usrHbidIntroducer;
	}

	public void setUsrHbidIntroducer(BigDecimal usrHbidIntroducer) {
		this.usrHbidIntroducer = usrHbidIntroducer;
	}

	@Column(name = "USR_HBID_MANAGER", precision = 22, scale = 0)
	public BigDecimal getUsrHbidManager() {
		return this.usrHbidManager;
	}

	public void setUsrHbidManager(BigDecimal usrHbidManager) {
		this.usrHbidManager = usrHbidManager;
	}

	@Column(name = "ROG_HBID", precision = 22, scale = 0)
	public BigDecimal getOrigin() {
		return this.origin;
	}

	public void setOrigin(BigDecimal origin) {
		this.origin = origin;
	}

	
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RTY_HBID")
	public Hbrequesttypes getType() {
		return this.type;
	}

	public void setType(Hbrequesttypes type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_INTRODUCTIONDATETIME", nullable = false, length = 7)
	public Date getRequested_datetime() {
		return this.requested_datetime;
	}

	public void setRequested_datetime(Date rqtIntroductiondatetime) {
		this.requested_datetime = rqtIntroductiondatetime;
	}

	@Column(name = "RQT_CREATIONDESCRIPTION", nullable = false, length = 4000)
	public String getRqtCreationdescription() {
		return this.rqtCreationdescription;
	}

	public void setRqtCreationdescription(String rqtCreationdescription) {
		this.rqtCreationdescription = rqtCreationdescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_REQUESTDATETIME", length = 7)
	public Date getRqtRequestdatetime() {
		return this.rqtRequestdatetime;
	}

	public void setRqtRequestdatetime(Date rqtRequestdatetime) {
		this.rqtRequestdatetime = rqtRequestdatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_REQUESTDATE", length = 7)
	public Date getRqtRequestdate() {
		return this.rqtRequestdate;
	}

	public void setRqtRequestdate(Date rqtRequestdate) {
		this.rqtRequestdate = rqtRequestdate;
	}

	@Column(name = "RQT_REQUESTNUMBER", precision = 22, scale = 0)
	public BigDecimal getService_request_id() {
		return this.service_request_id;
	}

	public void setService_request_id(BigDecimal service_request_id) {
		this.service_request_id = service_request_id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_EXPECTEDRESOLUTIONDATETIME", length = 7)
	public Date getRqtExpectedresolutiondatetime() {
		return this.rqtExpectedresolutiondatetime;
	}

	public void setRqtExpectedresolutiondatetime(Date rqtExpectedresolutiondatetime) {
		this.rqtExpectedresolutiondatetime = rqtExpectedresolutiondatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_CLOSEDATETIME", length = 7)
	public Date getUpdated_datetime() {
		return this.updated_datetime;
	}

	public void setUpdated_datetime(Date updated_datetime) {
		this.updated_datetime = updated_datetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_CLOSEDATE", length = 7)
	public Date getRqtClosedate() {
		return this.rqtClosedate;
	}

	public void setRqtClosedate(Date rqtClosedate) {
		this.rqtClosedate = rqtClosedate;
	}

	@Column(name = "MAC_HBID_MACHINE", precision = 22, scale = 0)
	public BigDecimal getMacHbidMachine() {
		return this.macHbidMachine;
	}

	public void setMacHbidMachine(BigDecimal macHbidMachine) {
		this.macHbidMachine = macHbidMachine;
	}

	@Column(name = "NUMREFCASD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumrefcasd() {
		return this.numrefcasd;
	}

	public void setNumrefcasd(BigDecimal numrefcasd) {
		this.numrefcasd = numrefcasd;
	}

	@Column(name = "IDCASD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdcasd() {
		return this.idcasd;
	}

	public void setIdcasd(BigDecimal idcasd) {
		this.idcasd = idcasd;
	}

	@Column(name = "RQT_REQUESTHOUR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRqtRequesthour() {
		return this.rqtRequesthour;
	}

	public void setRqtRequesthour(BigDecimal rqtRequesthour) {
		this.rqtRequesthour = rqtRequesthour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_RESOLVEDDATATIME", length = 7)
	public Date getRqtResolveddatatime() {
		return this.rqtResolveddatatime;
	}

	public void setRqtResolveddatatime(Date rqtResolveddatatime) {
		this.rqtResolveddatatime = rqtResolveddatatime;
	}

	@Column(name = "RQT_PARENT_ID", precision = 22, scale = 0)
	public BigDecimal getRqtParentId() {
		return this.rqtParentId;
	}

	public void setRqtParentId(BigDecimal rqtParentId) {
		this.rqtParentId = rqtParentId;
	}

	@Column(name = "RQT_PUBLIC", nullable = false, length = 1)
	public String getRqtPublic() {
		return this.rqtPublic;
	}

	public void setRqtPublic(String rqtPublic) {
		this.rqtPublic = rqtPublic;
	}

	@Column(name = "RQT_VALIDATED", nullable = false, length = 1)
	public String getValidated() {
		return this.validated;
	}

	public void setValidated(String validated) {
		this.validated = validated;
	}

	@Column(name = "RQT_GEOLOCATION")
	public String getRqtGeolocation() {
		return this.rqtGeolocation;
	}

	public void setRqtGeolocation(String rqtGeolocation) {
		this.rqtGeolocation = rqtGeolocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_GESTORDATE", length = 7)
	public Date getRqtGestordate() {
		return this.rqtGestordate;
	}

	public void setRqtGestordate(Date rqtGestordate) {
		this.rqtGestordate = rqtGestordate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_EXTERNODATE", length = 7)
	public Date getRqtExternodate() {
		return this.rqtExternodate;
	}

	public void setRqtExternodate(Date rqtExternodate) {
		this.rqtExternodate = rqtExternodate;
	}

	@Column(name = "OPERADOR", length = 40)
	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}

	@Column(name = "SOLICITA_RESPUESTA", length = 1)
	public String getAnswerRequested() {
		return this.answerRequested;
	}

	public void setAnswerRequested(String answerRequested) {
		this.answerRequested = answerRequested;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RQT_INSPECTORDATE", length = 7)
	public Date getRqtInspectordate() {
		return this.rqtInspectordate;
	}

	public void setRqtInspectordate(Date rqtInspectordate) {
		this.rqtInspectordate = rqtInspectordate;
	}

	@Column(name = "RQT_INSPECTORID", length = 60)
	public String getInterno_code() {
		return this.interno_code;
	}

	public void setInterno_code(String internoCode) {
		this.interno_code = internoCode;
	}

	@Column(name = "RQT_ZONAINSPECCIONID", precision = 22, scale = 0)
	public BigDecimal getRqtZonainspeccionid() {
		return this.rqtZonainspeccionid;
	}

	public void setRqtZonainspeccionid(BigDecimal rqtZonainspeccionid) {
		this.rqtZonainspeccionid = rqtZonainspeccionid;
	}

	@Column(name = "INTERNAL_STATUS", precision = 22, scale = 0)
	public BigDecimal getInternalStatus() {
		return this.internalStatus;
	}

	public void setInternalStatus(BigDecimal internalStatus) {
		this.internalStatus = internalStatus;
	}

	@Column(name = "NOTES", length = 2000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "ID_CITA", precision = 38, scale = 0)
	public BigDecimal getIdCita() {
		return this.idCita;
	}

	public void setIdCita(BigDecimal idCita) {
		this.idCita = idCita;
	}

	@Column(name = "TOKEN", length = 40)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TITLE", length = 600)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FIRST_NAME", length = 600)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "EMAIL", length = 300)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "USER_ADDRESS", length = 500)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "ADDRESS_STRING", length = 500)
	public String getAddressString() {
		return this.addressString;
	}

	public void setAddressString(String addressString) {
		this.addressString = addressString;
	}

//	@Transient
//	public Integer getAddressId() {
//		return this.portal.getId();
//	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}
	
	@Column(name = "X", nullable = true, precision = 10, scale = 2)
	public BigDecimal getX() {
		return x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}
	 @Column(name = "Y", nullable = true, precision = 10, scale = 2)
	public BigDecimal getY() {
		return y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

	@Transient
	public Punto getGeometry() {
		if (getX() != null) {
			geometry = new Punto(Punto.POINT, new Double[] {
					getX().doubleValue(), getY().doubleValue() });
		}
		return geometry;
	}

	public void setGeometry(Punto geometry) {
		if (geometry != null) {
			if (geometry.formatoWgs84()) {
				geometry.setCoordinates(Geometria.pasarAUTM30(
						geometry.getCoordinates()[0],
						geometry.getCoordinates()[1]));
			}
			this.x = BigDecimal.valueOf(geometry.getCoordinates()[0]);
			this.y = BigDecimal.valueOf(geometry.getCoordinates()[1]);
		}
		this.geometry = geometry;
	}
	
	@Column(name = "SERVICE_NOTICE", length = 4000)
	public String getService_notice() {
		return this.service_notice;
	}

	public void setService_notice(String serviceNotice) {
		this.service_notice = serviceNotice;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hbrequests")
	public List<Hbrequestactions> getActions() {
		return this.actions;
	}

	public void setActions(List<Hbrequestactions> actions) {
		this.actions = actions;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hbrequests")
	public List<Hbrequestloadfiles> getAttachments() {
		return attachments;
	}

	public void setAttachments(List<Hbrequestloadfiles> attachments) {
		this.attachments = attachments;
	}

	@Transient
	public String getStatus() {
		return this.getRqtClosedate() == null ? "open" : "closed";
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Transient
	public BigDecimal getService_code() {
		return this.getHbcategories() == null ? null : this.getHbcategories().getCalHbid();
	}

	public void setService_code(BigDecimal service_code) {
		this.service_code = service_code;
	}
	
	@Transient
	public String getService_name() {
		return this.getHbcategories() == null ? null : this.getHbcategories().getCalName();
	}

	@Transient
	public String getStatus_admin() {
		return this.getHbrequeststates() == null ? null : this.getHbrequeststates().getRstName();
	}
	
	public void setService_name(String service_name) {
		this.service_name = service_name;
	}
	@Transient
	public String getUri() {
		return Funciones.obtenerPath(this.getClass()) + getService_request_id();
	}
	
//	@OneToOne
//    @JoinColumn(name = "ADDRESS_ID", referencedColumnName="ID_POR", nullable = true)
//    @NotFound(action=NotFoundAction.IGNORE)
//    @SoloEnEstaEntidad
//	public Portalero getPortal() {
//		return portal;
//	}
//
//	public void setPortal(Portalero portal) {
//		this.portal = portal;
//	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cat_sip")
	@BatchSize(size=50)
	@NotNull
	public CategoriaSIP getCatSip() {
		return catSip;
	}
	
	public void setCatSip(CategoriaSIP catSip) {
		this.catSip = catSip;
	}

	@Transient
	public String getRdf() {
		if (getX() != null && getY() != null) {
			double[] coord = (double[])Geometria.transform(getX().doubleValue(), getY().doubleValue(), CheckeoParametros.SRSUTM30N, CheckeoParametros.SRSWGS84);
			
			return "<div property=\"geo\" typeof=\"GeoCoordinates\">"
	            + "<meta property=\"latitude\" content=\"" + coord[1] + "\"></meta>"
	            + "<meta property=\"longitude\" content=\"" + coord[0] + "\"></meta>"
	        + "</div>";
			
		} else {
			return null;
		}
	}
	
}
