package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.BatchSize;
import org.sede.core.anotaciones.Interno;
import org.sede.core.utils.Propiedades;
import org.sede.servicio.qys.ConfigQys;

/**
 * Hbrequestloadfiles generated by hbm2java
 */
@XmlRootElement(name="attachment")
@Entity
@Table(name = "HBREQUESTLOADFILES", schema = ConfigQys.ESQUEMA)
@BatchSize(size = 50)
public class Hbrequestloadfiles implements java.io.Serializable {

	private BigDecimal rlfHbid;
	private BigDecimal rlfHbversion;
	private String description;
	private String filename;
	@Interno
	private Hbrequests hbrequests;
	private BigDecimal usrHbidUserloadfile;
	private Date rlfIntrodutiondatetime;

	private String media_url;
	
	public Hbrequestloadfiles() {
	}

	public Hbrequestloadfiles(BigDecimal rlfHbid, BigDecimal rlfHbversion, String rlfDescription, String rlfFilename,
			Hbrequests hbrequests, Date rlfIntrodutiondatetime) {
		this.rlfHbid = rlfHbid;
		this.rlfHbversion = rlfHbversion;
		this.description = rlfDescription;
		this.filename = rlfFilename;
		this.hbrequests = hbrequests;
		this.rlfIntrodutiondatetime = rlfIntrodutiondatetime;
	}

	public Hbrequestloadfiles(BigDecimal rlfHbid, BigDecimal rlfHbversion, String rlfDescription, String rlfFilename,
			Hbrequests hbrequests, BigDecimal usrHbidUserloadfile, Date rlfIntrodutiondatetime) {
		this.rlfHbid = rlfHbid;
		this.rlfHbversion = rlfHbversion;
		this.description = rlfDescription;
		this.filename = rlfFilename;
		this.hbrequests = hbrequests;
		this.usrHbidUserloadfile = usrHbidUserloadfile;
		this.rlfIntrodutiondatetime = rlfIntrodutiondatetime;
	}

	@Id
	@Column(name = "RLF_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRlfHbid() {
		return this.rlfHbid;
	}

	public void setRlfHbid(BigDecimal rlfHbid) {
		this.rlfHbid = rlfHbid;
	}

	@Column(name = "RLF_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRlfHbversion() {
		return this.rlfHbversion;
	}

	public void setRlfHbversion(BigDecimal rlfHbversion) {
		this.rlfHbversion = rlfHbversion;
	}

	@Column(name = "RLF_DESCRIPTION", nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String rlfDescription) {
		this.description = rlfDescription;
	}

	@Column(name = "RLF_FILENAME", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String rlfFilename) {
		this.filename = rlfFilename;
	}
	
	@Column(name = "USR_HBID_USERLOADFILE", precision = 22, scale = 0)
	public BigDecimal getUsrHbidUserloadfile() {
		return this.usrHbidUserloadfile;
	}

	public void setUsrHbidUserloadfile(BigDecimal usrHbidUserloadfile) {
		this.usrHbidUserloadfile = usrHbidUserloadfile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RLF_INTRODUTIONDATETIME", nullable = false, length = 7)
	public Date getRlfIntrodutiondatetime() {
		return this.rlfIntrodutiondatetime;
	}

	public void setRlfIntrodutiondatetime(Date rlfIntrodutiondatetime) {
		this.rlfIntrodutiondatetime = rlfIntrodutiondatetime;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RQT_HBID_REQUEST", nullable = false, insertable = false, updatable = false)
	public Hbrequests getHbrequests() {
		return this.hbrequests;
	}

	public void setHbrequests(Hbrequests hbrequests) {
		this.hbrequests = hbrequests;
	}
	
	@Transient
	public String getMedia_url() {
		return Propiedades.getContexto() + "/servicio/quejas-sugerencias/" + this.hbrequests.getRqtHbid() + "/file/" + this.getRlfHbid();
	}

	public void setMedia_url(String media_url) {
		this.media_url = media_url;
	}
	
}
