package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Hbrequestactiontypes generated by hbm2java
 */
@XmlRootElement(name="request-action-type")
@Entity
@Table(name = "HBREQUESTACTIONTYPES", schema = "TICKETING", uniqueConstraints = @UniqueConstraint(columnNames = "RAT_NAME"))
public class Hbrequestactiontypes implements java.io.Serializable {

	private BigDecimal ratHbid;
	private BigDecimal ratHbversion;
	private String ratName;
	private BigDecimal ratDefault;

	public Hbrequestactiontypes() {
	}

	public Hbrequestactiontypes(BigDecimal ratHbid, BigDecimal ratHbversion, String ratName, BigDecimal ratDefault) {
		this.ratHbid = ratHbid;
		this.ratHbversion = ratHbversion;
		this.ratName = ratName;
		this.ratDefault = ratDefault;
	}

	@Id

	@Column(name = "RAT_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRatHbid() {
		return this.ratHbid;
	}

	public void setRatHbid(BigDecimal ratHbid) {
		this.ratHbid = ratHbid;
	}

	@Column(name = "RAT_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRatHbversion() {
		return this.ratHbversion;
	}

	public void setRatHbversion(BigDecimal ratHbversion) {
		this.ratHbversion = ratHbversion;
	}

	@Column(name = "RAT_NAME", unique = true, nullable = false, length = 30)
	public String getRatName() {
		return this.ratName;
	}

	public void setRatName(String ratName) {
		this.ratName = ratName;
	}

	@Column(name = "RAT_DEFAULT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRatDefault() {
		return this.ratDefault;
	}

	public void setRatDefault(BigDecimal ratDefault) {
		this.ratDefault = ratDefault;
	}

}
