package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;

/**
 * Hbscalinggroups generated by hbm2java
 */
@XmlRootElement(name="scaling-group")
@Entity
@Table(name = "HBSCALINGGROUPS", schema = "TICKETING", uniqueConstraints = @UniqueConstraint(columnNames = "SGP_NAME"))
public class Hbscalinggroups implements java.io.Serializable {

	private BigDecimal sgpHbid;
	private String sgpName;
	private BigDecimal sgpHbversion;
	private String sgpEmailgroup;
	private BigDecimal sgpAutonotification;
	@Interno
	private Set<Hbrequests> hbrequestses = new HashSet<Hbrequests>(0);

	public Hbscalinggroups() {
	}

	public Hbscalinggroups(BigDecimal sgpHbid, String sgpName, BigDecimal sgpHbversion, String sgpEmailgroup,
			BigDecimal sgpAutonotification) {
		this.sgpHbid = sgpHbid;
		this.sgpName = sgpName;
		this.sgpHbversion = sgpHbversion;
		this.sgpEmailgroup = sgpEmailgroup;
		this.sgpAutonotification = sgpAutonotification;
	}

	public Hbscalinggroups(BigDecimal sgpHbid, String sgpName, BigDecimal sgpHbversion, String sgpEmailgroup,
			BigDecimal sgpAutonotification, Set<Hbrequests> hbrequestses) {
		this.sgpHbid = sgpHbid;
		this.sgpName = sgpName;
		this.sgpHbversion = sgpHbversion;
		this.sgpEmailgroup = sgpEmailgroup;
		this.sgpAutonotification = sgpAutonotification;
		this.hbrequestses = hbrequestses;
	}

	@Id

	@Column(name = "SGP_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSgpHbid() {
		return this.sgpHbid;
	}

	public void setSgpHbid(BigDecimal sgpHbid) {
		this.sgpHbid = sgpHbid;
	}

	@Column(name = "SGP_NAME", unique = true, nullable = false, length = 30)
	public String getSgpName() {
		return this.sgpName;
	}

	public void setSgpName(String sgpName) {
		this.sgpName = sgpName;
	}

	@Column(name = "SGP_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSgpHbversion() {
		return this.sgpHbversion;
	}

	public void setSgpHbversion(BigDecimal sgpHbversion) {
		this.sgpHbversion = sgpHbversion;
	}

	@Column(name = "SGP_EMAILGROUP", nullable = false)
	public String getSgpEmailgroup() {
		return this.sgpEmailgroup;
	}

	public void setSgpEmailgroup(String sgpEmailgroup) {
		this.sgpEmailgroup = sgpEmailgroup;
	}

	@Column(name = "SGP_AUTONOTIFICATION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSgpAutonotification() {
		return this.sgpAutonotification;
	}

	public void setSgpAutonotification(BigDecimal sgpAutonotification) {
		this.sgpAutonotification = sgpAutonotification;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hbscalinggroups")
	public Set<Hbrequests> getHbrequestses() {
		return this.hbrequestses;
	}

	public void setHbrequestses(Set<Hbrequests> hbrequestses) {
		this.hbrequestses = hbrequestses;
	}

}
