/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HbscalinggroupusersId generated by hbm2java
 */
@Embeddable
public class HbscalinggroupusersId implements java.io.Serializable {

	private BigDecimal usrHbid;
	private BigDecimal sgpHbid;

	public HbscalinggroupusersId() {
	}

	public HbscalinggroupusersId(BigDecimal usrHbid, BigDecimal sgpHbid) {
		this.usrHbid = usrHbid;
		this.sgpHbid = sgpHbid;
	}

	@Column(name = "USR_HBID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbid() {
		return this.usrHbid;
	}

	public void setUsrHbid(BigDecimal usrHbid) {
		this.usrHbid = usrHbid;
	}

	@Column(name = "SGP_HBID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSgpHbid() {
		return this.sgpHbid;
	}

	public void setSgpHbid(BigDecimal sgpHbid) {
		this.sgpHbid = sgpHbid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HbscalinggroupusersId))
			return false;
		HbscalinggroupusersId castOther = (HbscalinggroupusersId) other;

		return ((this.getUsrHbid() == castOther.getUsrHbid()) || (this.getUsrHbid() != null
				&& castOther.getUsrHbid() != null && this.getUsrHbid().equals(castOther.getUsrHbid())))
				&& ((this.getSgpHbid() == castOther.getSgpHbid()) || (this.getSgpHbid() != null
						&& castOther.getSgpHbid() != null && this.getSgpHbid().equals(castOther.getSgpHbid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsrHbid() == null ? 0 : this.getUsrHbid().hashCode());
		result = 37 * result + (getSgpHbid() == null ? 0 : this.getSgpHbid().hashCode());
		return result;
	}

}
