/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.servicio.qys.ConfigQys;

/**
 * Hbscalinggroupusers generated by hbm2java
 */
@XmlRootElement(name="scaling-group-user")
@Entity
@Table(name = "HBSCALINGGROUPUSERS", schema = ConfigQys.ESQUEMA)
public class Hbscalinggroupusers implements java.io.Serializable {

	private HbscalinggroupusersId id;

	public Hbscalinggroupusers() {
	}

	public Hbscalinggroupusers(HbscalinggroupusersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "usrHbid", column = @Column(name = "USR_HBID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "sgpHbid", column = @Column(name = "SGP_HBID", nullable = false, precision = 22, scale = 0)) })
	public HbscalinggroupusersId getId() {
		return this.id;
	}

	public void setId(HbscalinggroupusersId id) {
		this.id = id;
	}

}
