package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HbusersOriginId generated by hbm2java
 */
@Embeddable
public class HbusersOriginId implements java.io.Serializable {

	private BigDecimal idUser;
	private BigDecimal idOrigin;

	public HbusersOriginId() {
	}

	public HbusersOriginId(BigDecimal idUser, BigDecimal idOrigin) {
		this.idUser = idUser;
		this.idOrigin = idOrigin;
	}

	@Column(name = "ID_USER", precision = 22, scale = 0)
	public BigDecimal getIdUser() {
		return this.idUser;
	}

	public void setIdUser(BigDecimal idUser) {
		this.idUser = idUser;
	}

	@Column(name = "ID_ORIGIN", precision = 22, scale = 0)
	public BigDecimal getIdOrigin() {
		return this.idOrigin;
	}

	public void setIdOrigin(BigDecimal idOrigin) {
		this.idOrigin = idOrigin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HbusersOriginId))
			return false;
		HbusersOriginId castOther = (HbusersOriginId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null
				&& castOther.getIdUser() != null && this.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getIdOrigin() == castOther.getIdOrigin()) || (this.getIdOrigin() != null
						&& castOther.getIdOrigin() != null && this.getIdOrigin().equals(castOther.getIdOrigin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result + (getIdOrigin() == null ? 0 : this.getIdOrigin().hashCode());
		return result;
	}

}
