/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;
import org.sede.servicio.qys.ConfigQys;

/**
 * Hbusers generated by hbm2java
 */
@XmlRootElement(name="user")
@Entity
@Table(name = "HBUSERS", schema = ConfigQys.ESQUEMA, uniqueConstraints = @UniqueConstraint(columnNames = "USR_USERNAME"))
public class Hbusers implements java.io.Serializable {

	private BigDecimal usrHbid;
	private String usrUsername;
	private BigDecimal usrHbidDepartment;
	private String perFirstname;
	private String perLastname;
	private String perPhone1;
	private String perPhone2;
	private String perExt;
	private String perMovile;
	private String cliPlacement;
	private String cliEmail;
	private String cliCompany;
	private String cliTreatment;
	private String cliPosition;
	private BigDecimal usrHbversion;
	private String usrHbtypediscriminator;
	private BigDecimal idcasd;
	private BigDecimal usrHbidCompany;
	private BigDecimal cliIdZone;
	private BigDecimal cliIdCategory;
	private BigDecimal cliCategory;
	private String cliOthers;
	private String perAddress;
	private String perCity;
	private String perCountry;
	private String perZipcode;
	private String perNif;
	@Interno
	private Set<HbusersOrigin> hbusersOrigins = new HashSet<HbusersOrigin>(0);
	@Interno
	private Set<Respuestastipo> respuestastipos = new HashSet<Respuestastipo>(0);

	public Hbusers() {
	}

	public Hbusers(BigDecimal usrHbid, String usrUsername, String usrPassword, BigDecimal usrHbidDepartment,
			String perFirstname, String perLastname, String perPhone1, String perPhone2, String perExt,
			String perMovile, String cliPlacement, String cliEmail, String cliCompany, String cliTreatment,
			String cliPosition, BigDecimal usrHbversion, String usrHbtypediscriminator, BigDecimal idcasd,
			BigDecimal usrHbidCompany, BigDecimal cliCategory, String cliOthers, String perAddress, String perCity,
			String perCountry, String perZipcode, String perNif) {
		this.usrHbid = usrHbid;
		this.usrUsername = usrUsername;
		this.usrHbidDepartment = usrHbidDepartment;
		this.perFirstname = perFirstname;
		this.perLastname = perLastname;
		this.perPhone1 = perPhone1;
		this.perPhone2 = perPhone2;
		this.perExt = perExt;
		this.perMovile = perMovile;
		this.cliPlacement = cliPlacement;
		this.cliEmail = cliEmail;
		this.cliCompany = cliCompany;
		this.cliTreatment = cliTreatment;
		this.cliPosition = cliPosition;
		this.usrHbversion = usrHbversion;
		this.usrHbtypediscriminator = usrHbtypediscriminator;
		this.idcasd = idcasd;
		this.usrHbidCompany = usrHbidCompany;
		this.cliCategory = cliCategory;
		this.cliOthers = cliOthers;
		this.perAddress = perAddress;
		this.perCity = perCity;
		this.perCountry = perCountry;
		this.perZipcode = perZipcode;
		this.perNif = perNif;
	}

	public Hbusers(BigDecimal usrHbid, String usrUsername, BigDecimal usrHbidDepartment,
			String perFirstname, String perLastname, String perPhone1, String perPhone2, String perExt,
			String perMovile, String cliPlacement, String cliEmail, String cliCompany, String cliTreatment,
			String cliPosition, BigDecimal usrHbversion, String usrHbtypediscriminator, BigDecimal idcasd,
			BigDecimal usrHbidCompany, BigDecimal cliIdZone, BigDecimal cliIdCategory, BigDecimal cliCategory,
			String cliOthers, String perAddress, String perCity, String perCountry, String perZipcode, String perNif,
			Set<HbusersOrigin> hbusersOrigins, Set<Respuestastipo> respuestastipos) {
		this.usrHbid = usrHbid;
		this.usrUsername = usrUsername;
		this.usrHbidDepartment = usrHbidDepartment;
		this.perFirstname = perFirstname;
		this.perLastname = perLastname;
		this.perPhone1 = perPhone1;
		this.perPhone2 = perPhone2;
		this.perExt = perExt;
		this.perMovile = perMovile;
		this.cliPlacement = cliPlacement;
		this.cliEmail = cliEmail;
		this.cliCompany = cliCompany;
		this.cliTreatment = cliTreatment;
		this.cliPosition = cliPosition;
		this.usrHbversion = usrHbversion;
		this.usrHbtypediscriminator = usrHbtypediscriminator;
		this.idcasd = idcasd;
		this.usrHbidCompany = usrHbidCompany;
		this.cliIdZone = cliIdZone;
		this.cliIdCategory = cliIdCategory;
		this.cliCategory = cliCategory;
		this.cliOthers = cliOthers;
		this.perAddress = perAddress;
		this.perCity = perCity;
		this.perCountry = perCountry;
		this.perZipcode = perZipcode;
		this.perNif = perNif;
		this.hbusersOrigins = hbusersOrigins;
		this.respuestastipos = respuestastipos;
	}

	@Id
	@Column(name = "USR_HBID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbid() {
		return this.usrHbid;
	}

	public void setUsrHbid(BigDecimal usrHbid) {
		this.usrHbid = usrHbid;
	}

	@Column(name = "USR_USERNAME", unique = true, nullable = false, length = 125)
	public String getUsrUsername() {
		return this.usrUsername;
	}

	public void setUsrUsername(String usrUsername) {
		this.usrUsername = usrUsername;
	}

	@Column(name = "USR_HBID_DEPARTMENT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbidDepartment() {
		return this.usrHbidDepartment;
	}

	public void setUsrHbidDepartment(BigDecimal usrHbidDepartment) {
		this.usrHbidDepartment = usrHbidDepartment;
	}

	@Column(name = "PER_FIRSTNAME", nullable = false, length = 30)
	public String getPerFirstname() {
		return this.perFirstname;
	}

	public void setPerFirstname(String perFirstname) {
		this.perFirstname = perFirstname;
	}

	@Column(name = "PER_LASTNAME", nullable = false, length = 40)
	public String getPerLastname() {
		return this.perLastname;
	}

	public void setPerLastname(String perLastname) {
		this.perLastname = perLastname;
	}

	@Column(name = "PER_PHONE1", nullable = false, length = 50)
	public String getPerPhone1() {
		return this.perPhone1;
	}

	public void setPerPhone1(String perPhone1) {
		this.perPhone1 = perPhone1;
	}

	@Column(name = "PER_PHONE2", nullable = false, length = 50)
	public String getPerPhone2() {
		return this.perPhone2;
	}

	public void setPerPhone2(String perPhone2) {
		this.perPhone2 = perPhone2;
	}

	@Column(name = "PER_EXT", nullable = false, length = 50)
	public String getPerExt() {
		return this.perExt;
	}

	public void setPerExt(String perExt) {
		this.perExt = perExt;
	}

	@Column(name = "PER_MOVILE", nullable = false, length = 50)
	public String getPerMovile() {
		return this.perMovile;
	}

	public void setPerMovile(String perMovile) {
		this.perMovile = perMovile;
	}

	@Column(name = "CLI_PLACEMENT", nullable = false, length = 30)
	public String getCliPlacement() {
		return this.cliPlacement;
	}

	public void setCliPlacement(String cliPlacement) {
		this.cliPlacement = cliPlacement;
	}

	@Column(name = "CLI_EMAIL", nullable = false)
	public String getCliEmail() {
		return this.cliEmail;
	}

	public void setCliEmail(String cliEmail) {
		this.cliEmail = cliEmail;
	}

	@Column(name = "CLI_COMPANY", nullable = false, length = 50)
	public String getCliCompany() {
		return this.cliCompany;
	}

	public void setCliCompany(String cliCompany) {
		this.cliCompany = cliCompany;
	}

	@Column(name = "CLI_TREATMENT", nullable = false, length = 20)
	public String getCliTreatment() {
		return this.cliTreatment;
	}

	public void setCliTreatment(String cliTreatment) {
		this.cliTreatment = cliTreatment;
	}

	@Column(name = "CLI_POSITION", nullable = false, length = 30)
	public String getCliPosition() {
		return this.cliPosition;
	}

	public void setCliPosition(String cliPosition) {
		this.cliPosition = cliPosition;
	}

	@Column(name = "USR_HBVERSION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbversion() {
		return this.usrHbversion;
	}

	public void setUsrHbversion(BigDecimal usrHbversion) {
		this.usrHbversion = usrHbversion;
	}

	@Column(name = "USR_HBTYPEDISCRIMINATOR", nullable = false, length = 10)
	public String getUsrHbtypediscriminator() {
		return this.usrHbtypediscriminator;
	}

	public void setUsrHbtypediscriminator(String usrHbtypediscriminator) {
		this.usrHbtypediscriminator = usrHbtypediscriminator;
	}

	@Column(name = "IDCASD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdcasd() {
		return this.idcasd;
	}

	public void setIdcasd(BigDecimal idcasd) {
		this.idcasd = idcasd;
	}

	@Column(name = "USR_HBID_COMPANY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsrHbidCompany() {
		return this.usrHbidCompany;
	}

	public void setUsrHbidCompany(BigDecimal usrHbidCompany) {
		this.usrHbidCompany = usrHbidCompany;
	}

	@Column(name = "CLI_ID_ZONE", precision = 22, scale = 0)
	public BigDecimal getCliIdZone() {
		return this.cliIdZone;
	}

	public void setCliIdZone(BigDecimal cliIdZone) {
		this.cliIdZone = cliIdZone;
	}

	@Column(name = "CLI_ID_CATEGORY", precision = 22, scale = 0)
	public BigDecimal getCliIdCategory() {
		return this.cliIdCategory;
	}

	public void setCliIdCategory(BigDecimal cliIdCategory) {
		this.cliIdCategory = cliIdCategory;
	}

	@Column(name = "CLI_CATEGORY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCliCategory() {
		return this.cliCategory;
	}

	public void setCliCategory(BigDecimal cliCategory) {
		this.cliCategory = cliCategory;
	}

	@Column(name = "CLI_OTHERS", nullable = false, length = 4000)
	public String getCliOthers() {
		return this.cliOthers;
	}

	public void setCliOthers(String cliOthers) {
		this.cliOthers = cliOthers;
	}

	@Column(name = "PER_ADDRESS", nullable = false)
	public String getPerAddress() {
		return this.perAddress;
	}

	public void setPerAddress(String perAddress) {
		this.perAddress = perAddress;
	}

	@Column(name = "PER_CITY", nullable = false, length = 30)
	public String getPerCity() {
		return this.perCity;
	}

	public void setPerCity(String perCity) {
		this.perCity = perCity;
	}

	@Column(name = "PER_COUNTRY", nullable = false, length = 30)
	public String getPerCountry() {
		return this.perCountry;
	}

	public void setPerCountry(String perCountry) {
		this.perCountry = perCountry;
	}

	@Column(name = "PER_ZIPCODE", nullable = false, length = 10)
	public String getPerZipcode() {
		return this.perZipcode;
	}

	public void setPerZipcode(String perZipcode) {
		this.perZipcode = perZipcode;
	}

	@Column(name = "PER_NIF", nullable = false, length = 10)
	public String getPerNif() {
		return this.perNif;
	}

	public void setPerNif(String perNif) {
		this.perNif = perNif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hbusers")
	public Set<HbusersOrigin> getHbusersOrigins() {
		return this.hbusersOrigins;
	}

	public void setHbusersOrigins(Set<HbusersOrigin> hbusersOrigins) {
		this.hbusersOrigins = hbusersOrigins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hbusers")
	public Set<Respuestastipo> getRespuestastipos() {
		return this.respuestastipos;
	}

	public void setRespuestastipos(Set<Respuestastipo> respuestastipos) {
		this.respuestastipos = respuestastipos;
	}

}
