/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;
import org.sede.servicio.qys.ConfigQys;

/**
 * HbusersOrigin generated by hbm2java
 */
@XmlRootElement(name="origin")
@Entity
@Table(name = "HBUSERS_ORIGIN", schema = ConfigQys.ESQUEMA)
public class HbusersOrigin implements java.io.Serializable {

	@Interno
	private HbusersOriginId id;
	@Interno
	private Hbrequestorigins hbrequestorigins;
	@Interno
	private Hbusers hbusers;

	public HbusersOrigin() {
	}

	public HbusersOrigin(HbusersOriginId id) {
		this.id = id;
	}

	public HbusersOrigin(HbusersOriginId id, Hbrequestorigins hbrequestorigins, Hbusers hbusers) {
		this.id = id;
		this.hbrequestorigins = hbrequestorigins;
		this.hbusers = hbusers;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "ID_USER", precision = 22, scale = 0)),
			@AttributeOverride(name = "idOrigin", column = @Column(name = "ID_ORIGIN", precision = 22, scale = 0)) })
	public HbusersOriginId getId() {
		return this.id;
	}

	public void setId(HbusersOriginId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ORIGIN", insertable = false, updatable = false)
	public Hbrequestorigins getHbrequestorigins() {
		return this.hbrequestorigins;
	}

	public void setHbrequestorigins(Hbrequestorigins hbrequestorigins) {
		this.hbrequestorigins = hbrequestorigins;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", insertable = false, updatable = false)
	public Hbusers getHbusers() {
		return this.hbusers;
	}

	public void setHbusers(Hbusers hbusers) {
		this.hbusers = hbusers;
	}

}
