package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;

/**
 * Respuestastipo generated by hbm2java
 */
@XmlRootElement(name="respuesta-tipo")
@Entity
@Table(name = "RESPUESTASTIPO", schema = "TICKETING")
public class Respuestastipo implements java.io.Serializable {

	private RespuestastipoId id;
	@Interno
	private Hbusers hbusers;

	public Respuestastipo() {
	}

	public Respuestastipo(RespuestastipoId id) {
		this.id = id;
	}

	public Respuestastipo(RespuestastipoId id, Hbusers hbusers) {
		this.id = id;
		this.hbusers = hbusers;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", precision = 22, scale = 0)),
			@AttributeOverride(name = "texto", column = @Column(name = "TEXTO", length = 1000)) })
	public RespuestastipoId getId() {
		return this.id;
	}

	public void setId(RespuestastipoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", insertable = false, updatable = false)
	public Hbusers getHbusers() {
		return this.hbusers;
	}

	public void setHbusers(Hbusers hbusers) {
		this.hbusers = hbusers;
	}

}
