/* Copyright (C) 2020 Oficina Técnica de Participación, Transparenica y Gobierno Abierto del Ayuntamiento de Zaragoza
 * 
 * Este fichero es parte del "Quejas y Sugerencias - Open City Zaragoza".
 *
 * "Quejas y Sugerencias - Open City Zaragoza" es un software libre; usted puede utilizar esta obra respetando la licencia GNU General Public License, versión 3 o posterior, publicada por Free Software Foundation
 *
 * Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL», SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 * Véase la Licencia en el idioma concreto que rige los permisos y limitaciones que establece la Licencia. 
 *
 * Para más información, puede contactar con los autores en: gobiernoabierto@zaragoza.es, sedelectronica@zaragoza.es
 */

package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.sede.core.anotaciones.Interno;
import org.sede.servicio.qys.ConfigQys;

/**
 * Respuestastipo generated by hbm2java
 */
@XmlRootElement(name="respuesta-tipo")
@Entity
@Table(name = "RESPUESTASTIPO", schema = ConfigQys.ESQUEMA)
public class Respuestastipo implements java.io.Serializable {

	private RespuestastipoId id;
	@Interno
	private Hbusers hbusers;

	public Respuestastipo() {
	}

	public Respuestastipo(RespuestastipoId id) {
		this.id = id;
	}

	public Respuestastipo(RespuestastipoId id, Hbusers hbusers) {
		this.id = id;
		this.hbusers = hbusers;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", precision = 22, scale = 0)),
			@AttributeOverride(name = "texto", column = @Column(name = "TEXTO", length = 1000)) })
	public RespuestastipoId getId() {
		return this.id;
	}

	public void setId(RespuestastipoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", insertable = false, updatable = false)
	public Hbusers getHbusers() {
		return this.hbusers;
	}

	public void setHbusers(Hbusers hbusers) {
		this.hbusers = hbusers;
	}

}
