package org.sede.servicio.qys.entity.db;
// Generated 17-jul-2019 8:10:17 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RespuestastipoId generated by hbm2java
 */
@Embeddable
public class RespuestastipoId implements java.io.Serializable {

	private BigDecimal userId;
	private BigDecimal tipo;
	private String texto;

	public RespuestastipoId() {
	}

	public RespuestastipoId(BigDecimal userId, BigDecimal tipo, String texto) {
		this.userId = userId;
		this.tipo = tipo;
		this.texto = texto;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	@Column(name = "TIPO", precision = 22, scale = 0)
	public BigDecimal getTipo() {
		return this.tipo;
	}

	public void setTipo(BigDecimal tipo) {
		this.tipo = tipo;
	}

	@Column(name = "TEXTO", length = 1000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RespuestastipoId))
			return false;
		RespuestastipoId castOther = (RespuestastipoId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getTexto() == castOther.getTexto()) || (this.getTexto() != null
						&& castOther.getTexto() != null && this.getTexto().equals(castOther.getTexto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getTexto() == null ? 0 : this.getTexto().hashCode());
		return result;
	}

}
