
  CREATE TABLE "POI_AGRUPACION" 
   (	"ID_AGRUPACION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(45), 
	"GCZ_PUBLICADO" VARCHAR2(45) DEFAULT 'N', 
	"TIPO" VARCHAR2(45), 
	"GCZ_FECHAALTA" DATE DEFAULT sysdate, 
	"GCZ_FECHAMOD" DATE, 
	"GCZ_FECHAPUB" DATE, 
	"GCZ_USUARIOALTA" VARCHAR2(50), 
	"GCZ_USUARIOMOD" VARCHAR2(50), 
	"GCZ_USUARIOPUB" VARCHAR2(50), 
	"ICON" VARCHAR2(200)
   ) ;

  CREATE TABLE "POI_AGRUPACION_CATEGORY" 
   (	"ID_AGRUPACION" NUMBER, 
	"ID_CATEGORIA" NUMBER
   ) ;

  CREATE TABLE "POI_CATEGORIA" 
   (	"ID" NUMBER, 
	"VALOR" VARCHAR2(200), 
	"TIPO" NUMBER, 
	"GCZ_USUARIO" VARCHAR2(200)
   ) ;

  CREATE TABLE "POI_COMMENT" 
   (	"ID_POI" VARCHAR2(20), 
	"ID_AGRUPACION" NUMBER, 
	"ID_COMMENT" NUMBER, 
	"ID_USUARIO_ADENTRA" NUMBER, 
	"DESCRIPTION" VARCHAR2(400)
   ) ;

  CREATE TABLE "POI_ETIQUETA" 
   (	"ID_ETIQUETA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200), 
	"TIPO" NUMBER, 
	"ORDEN" NUMBER, 
	"SQL" VARCHAR2(500), 
	"NOMBRELARGO" VARCHAR2(100)
   ) ;

  CREATE TABLE "POI_INFO" 
   (	"ID_POI" VARCHAR2(100), 
	"ID_AGRUPACION" NUMBER(*,0), 
	"GCZ_PUBLICADO" VARCHAR2(45) DEFAULT 'N', 
	"GCZ_FECHAALTA" DATE DEFAULT sysdate, 
	"GCZ_FECHAMOD" DATE, 
	"GCZ_USUARIOALTA" VARCHAR2(100), 
	"GCZ_USUARIOMOD" VARCHAR2(100), 
	"GCZ_USUARIOPUB" VARCHAR2(100)
   ) ;

  CREATE TABLE "POI_VALOR_ETIQUETA" 
   (	"ID_POI" VARCHAR2(20), 
	"ID_ETIQUETA" NUMBER, 
	"VALOR" VARCHAR2(4000), 
	"ID_AGRUPACION" NUMBER
   ) ;

   CREATE TABLE "POI_AGRUPACION_ASSOCIATED_TYPE" 
   (	"ID_AGRUPACION" NUMBER, 
	"TIPO" VARCHAR2(40 BYTE), 
	"ASSOCIATED_ID" VARCHAR2(40 BYTE)
   ) ;
   
  CREATE UNIQUE INDEX "SYS_C00108580" ON "POI_AGRUPACION" ("ID_AGRUPACION") 
  ;

  CREATE UNIQUE INDEX "POI_AGRCAT_PK" ON "POI_AGRUPACION_CATEGORY" ("ID_AGRUPACION", "ID_CATEGORIA") 
  ;

  CREATE UNIQUE INDEX "POI_CATEGORIA_PK" ON "POI_CATEGORIA" ("ID") 
  ;
  CREATE UNIQUE INDEX "POI_COMMENT_PK" ON "POI_COMMENT" ("ID_POI", "ID_COMMENT", "ID_AGRUPACION") 
  ;

  CREATE UNIQUE INDEX "SYS_C00108579" ON "POI_ETIQUETA" ("ID_ETIQUETA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00108720" ON "POI_INFO" ("ID_POI", "ID_AGRUPACION") 
  ;

  CREATE UNIQUE INDEX "POI_VALOR_ETIQUETA_PK" ON "POI_VALOR_ETIQUETA" ("ID_POI", "ID_ETIQUETA", "ID_AGRUPACION") 
  ;

  ALTER TABLE "POI_AGRUPACION" ADD PRIMARY KEY ("ID_AGRUPACION") ENABLE;

  ALTER TABLE "POI_AGRUPACION_CATEGORY" ADD CONSTRAINT "POI_AGRCAT_PK" PRIMARY KEY ("ID_AGRUPACION", "ID_CATEGORIA") ENABLE;
 
  ALTER TABLE "POI_AGRUPACION_CATEGORY" MODIFY ("ID_AGRUPACION" NOT NULL ENABLE);
 
  ALTER TABLE "POI_AGRUPACION_CATEGORY" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);

  ALTER TABLE "POI_CATEGORIA" ADD CONSTRAINT "POI_CATEGORIA_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "POI_CATEGORIA" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "POI_COMMENT" ADD CONSTRAINT "POI_COMMENT_PK" PRIMARY KEY ("ID_POI", "ID_COMMENT", "ID_AGRUPACION") ENABLE;
 
  ALTER TABLE "POI_COMMENT" MODIFY ("ID_POI" NOT NULL ENABLE);
 
  ALTER TABLE "POI_COMMENT" MODIFY ("ID_AGRUPACION" NOT NULL ENABLE);
 
  ALTER TABLE "POI_COMMENT" MODIFY ("ID_COMMENT" NOT NULL ENABLE);
 
  ALTER TABLE "POI_COMMENT" MODIFY ("ID_USUARIO_ADENTRA" NOT NULL ENABLE);

  ALTER TABLE "POI_ETIQUETA" ADD PRIMARY KEY ("ID_ETIQUETA") ENABLE;

  ALTER TABLE "POI_INFO" MODIFY ("ID_POI" NOT NULL ENABLE);
 
  ALTER TABLE "POI_INFO" MODIFY ("ID_AGRUPACION" NOT NULL ENABLE);
 
  ALTER TABLE "POI_INFO" ADD PRIMARY KEY ("ID_POI", "ID_AGRUPACION") ENABLE;

  ALTER TABLE "POI_VALOR_ETIQUETA" ADD CONSTRAINT "POI_VALOR_ETIQUETA_PK" PRIMARY KEY ("ID_POI", "ID_ETIQUETA", "ID_AGRUPACION") ENABLE;
 
  ALTER TABLE "POI_VALOR_ETIQUETA" MODIFY ("ID_POI" NOT NULL ENABLE);
 
  ALTER TABLE "POI_VALOR_ETIQUETA" MODIFY ("ID_ETIQUETA" NOT NULL ENABLE);

  ALTER TABLE "POI_AGRUPACION_CATEGORY" ADD CONSTRAINT "POI_AGRCAT_FK1" FOREIGN KEY ("ID_AGRUPACION")
	  REFERENCES "POI_AGRUPACION" ("ID_AGRUPACION") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "POI_AGRUPACION_CATEGORY" ADD CONSTRAINT "POI_AGRCAT_FK2" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "POI_CATEGORIA" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "POI_COMMENT" ADD CONSTRAINT "POI_COMMENT_POI_IN_FK1" FOREIGN KEY ("ID_POI", "ID_AGRUPACION")
	  REFERENCES "POI_INFO" ("ID_POI", "ID_AGRUPACION") ON DELETE CASCADE ENABLE;

  ALTER TABLE "POI_INFO" ADD CONSTRAINT "POI_INFO_POI_AGRUPACION_FK1" FOREIGN KEY ("ID_AGRUPACION")
	  REFERENCES "POI_AGRUPACION" ("ID_AGRUPACION") ON DELETE CASCADE ENABLE;

  ALTER TABLE "POI_VALOR_ETIQUETA" ADD CONSTRAINT "POI_VALOR_ETIQUETA_POI_ET_FK1" FOREIGN KEY ("ID_ETIQUETA")
	  REFERENCES "POI_ETIQUETA" ("ID_ETIQUETA") ENABLE;
 
  ALTER TABLE "POI_VALOR_ETIQUETA" ADD CONSTRAINT "POI_VALOR_ETIQUETA_POI_IN_FK1" FOREIGN KEY ("ID_POI", "ID_AGRUPACION")
	  REFERENCES "POI_INFO" ("ID_POI", "ID_AGRUPACION") ON DELETE CASCADE ENABLE;

  CREATE UNIQUE INDEX "PK_AGR_ASSOCIATED" ON "POI_AGRUPACION_ASSOCIATED_TYPE" ("ID_AGRUPACION", "TIPO", "ASSOCIATED_ID");

  ALTER TABLE "POI_AGRUPACION_ASSOCIATED_TYPE" ADD CONSTRAINT "PK_AGR_ASSOCIATED" PRIMARY KEY ("ID_AGRUPACION", "TIPO", "ASSOCIATED_ID");
	  
  CREATE SEQUENCE  "SEQ_POI_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5521 CACHE 20 NOORDER  NOCYCLE ;