REM INSERTING into CATEGORIA_SIP
SET DEFINE OFF;
Insert into CATEGORIA_SIP (ID,TITLE) values ('1','Información institucional y organizativa (organigrama, competencias, perfil y trayectoria profesional, etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('2','Planes y programas operativos (plan de gobierno y otros planes/programas de actuación, resultados de su evaluación, etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('3','Normativa (normas locales y documentos emitidos en el procedimiento de elaboración, etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('4','Información económica (presupuestos y su ejecución, cuentas, informes de control externo, patrimonio, etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('5','Ayudas y subvenciones');
Insert into CATEGORIA_SIP (ID,TITLE) values ('6','Urbanismo');
Insert into CATEGORIA_SIP (ID,TITLE) values ('7','Contratación administrativa');
Insert into CATEGORIA_SIP (ID,TITLE) values ('8','Medio Ambiente');
Insert into CATEGORIA_SIP (ID,TITLE) values ('9','Recursos humanos (retribuciones, compatibilidades, procesos selectivos, provisión de puestos de trabajo, bolsas de empleo,etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('10','Relaciones con la ciudadanía y participación (cartas de servicio, sugerencias y reclamaciones, inventario de procedimientos, etc.)');
Insert into CATEGORIA_SIP (ID,TITLE) values ('11','Otros');
REM INSERTING into FO_HBREQACTIONSID_UNIQUE_KEY
SET DEFINE OFF;
Insert into FO_HBREQACTIONSID_UNIQUE_KEY (REQACTIONID) values ('2147437517');
REM INSERTING into FO_HBREQLOADFILESID_UNIQUE_KEY
SET DEFINE OFF;
Insert into FO_HBREQLOADFILESID_UNIQUE_KEY (FILEID) values ('2147478959');
REM INSERTING into FO_HBREQUESTSID_UNIQUE_KEY
SET DEFINE OFF;
Insert into FO_HBREQUESTSID_UNIQUE_KEY (REQUESTID) values ('2147438621');
REM INSERTING into FO_HBUSERSID_UNIQUE_KEY
SET DEFINE OFF;
Insert into FO_HBUSERSID_UNIQUE_KEY (USERID) values ('2147480310');
REM INSERTING into HBACTIONITEMTYPES
SET DEFINE OFF;
REM INSERTING into HBASSETENUMERATEDSTRPROPERTIES
SET DEFINE OFF;
REM INSERTING into HBASSETS
SET DEFINE OFF;
REM INSERTING into HBASSETSDATA
SET DEFINE OFF;
REM INSERTING into HBASSETTYPES
SET DEFINE OFF;
REM INSERTING into HBCATEGORIES
SET DEFINE OFF;
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('188088321',null,'Reforma integral calles','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849672',null,'Gestión de Residuos,Limpieza de calles,contenedores,Puntos Limpios','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849673',null,'Medio Ambiente, malos olores, Agenda 21, Sostenibilidad, Educación ambiental,Voluntariado','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849674',null,' ','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144576',null,'Pabellones y Centros Deportivos, Piscinas','1','1','1');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144577',null,'Problemas luz,farolas fundidas.','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5931009',null,'Cortes de Agua, denuncias de vertido de agua, saneamiento de tuberías, alcantarillas','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('7733248',null,'Transporte, Circulación,plazas aparcamientos, vallas. Señalización horizontal y vertical, pivotes. Obras Tranvía','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('24182784',null,'No conformidades según pautas WAI','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('97779712',null,'zona azul, amarilla','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4784129',null,' ','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('82182145',null,'Información sobre tramitación electrónica','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('82182147',null,'incidencias sobre Tarjeta Ciudadana','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('97550336',null,'lineas tuzsa,lineas barrios rurales,paradas bus,paradas colegios, marquesinas. Tranvía','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('102793216',null,'Wifi,milla digital,Jornadas Ciudad conocimiento, CAT,vivero empresas, DWP','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('103677952',null,'semáforos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('109740032',null,'consulta expedientes ','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('109740033',null,'Problemas acceso con certificado, tarjeta funcionarios','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849665',null,'Información turística: planos, fotos, visitas guidas','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5472256',null,'Matrículas, horarios, servicios y direcciones Escuelas Infantiles','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('6029312',null,'Documentos históricos y municipales, búsqueda de antepasados','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('9043968',null,'Nombres de calles,préstamo obras de arte,exposiciones','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('9043969',null,'Estaciones Bizi,carriles,circulaci¿n bicicletas','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('97779713',null,'señalización horizontal y vertical','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('109740034',null,'problemas carpeta ciudadana','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849668',null,'censos, convenios,subvenciones, consejo ciudad,asociaciones','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849669',null,'Incidencias en Vía Pública:aceras en mal estado,baldosas rotas,baches,pivotes','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849670',null,'Politica Municipal en general,correos directos al Alcalde','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849671',null,'Parques, Jardines, mobiliario infantil, aspersores,alcorques, podas, bancos, fuentes','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144579',null,'Salud Pública, plagas, protecci¿n animal, Higiene alimentaria, calidad de aguas, análisis de laboratorios.','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144580',null,'Concursos, actividades culturales','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144581',null,'Mayores,actividades,cursos,Centros Convivencia,Parques Mayores, Voluntariado del mayor','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144582',null,'Cementerio, nichos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144583',null,'Publicaciones municipales y concursos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144584',null,' ','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144585',null,'Bibliotecas municipales:actividades, edificios,horarios.','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144586',null,'Padron,Estadisticas,Elecciones,Censo electoral','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144587',null,'Información urbanística general, carteles calles','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('15564801',null,'Fiestas de Barrios, Venta Ambulante,Taxis','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('16777216',null,'Política internacional, Hermanamientos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('16777217',null,'Escuela de Música y Danza, Escuela de Teatro, Conservatorio Elemental de Música, Conservatorio Profesional de Danza','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('82182144',null,'Tribuna del Agua, informaci¿n ambiental','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('106954752',null,'actualizacion, falta de contenidos, enlaces rotos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('2',null,' ','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4030464',null,'General: Atención al ciudadano','1','1','1');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4030465',null,'facturas, contadores, cambios de titularidad','1','1','1');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849666',null,'Actuaciones policiales, Multas,objetos perdidos, autorizaciones en la calle,informes policiales,atestados,veh¿culos abandonados en v¿a p¿blica','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('4849667',null,'Peatonalización, ruido arquetas, retirada vallas y planchas metálicas de obras,renovaci¿n tuber¿as y calles,solicitud planos','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('5144578',null,'Actos y Permisos en Via publica,Fiestas,Pe¿as,Venta Ambulante,Mercados,Veladores,Tarjetas discapacitados, Mobiliario,Urbano,Publicidad (MUPIS)','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('6520832',null,'periodicos antiguos, revistas, boletines','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('118587392',null,'contadores, recibos y facturas agua','0','0','0');
Insert into HBCATEGORIES (CAT_HBID,RQT_HBID_TEMPLATECATEGORY,CAT_TEMPLATEREQUESTDESCRIPTION,CAT_EXPECTEDRESOLUTIONMINUTES,CAT_EXPECTRESOLUTIONMINREAL,CAT_OBJECTIVEPERCENTAGE) values ('184647680',null,'asuntos contestados directamente por Web Municipal','0','0','0');
REM INSERTING into HBCATEGORYLEVELS
SET DEFINE OFF;
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('2','1','3899392','1','Internal','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('188088321','0','3899392','1','Oficina Infraestructuras','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849672','0','3899392','1','Limpieza Pública','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849673','0','3899392','1','Medioambiente','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849674','1','3899392','1','Prueba','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144576','0','3899392','1','Instalaciones Deportivas','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144577','0','3899392','1','Alumbrado Publico','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('24182784','2','3899392','1','Accesibilidad','1','S');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5931009','0','3899392','1','Infraestructuras:Explotacion','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('7733248','0','3899392','1','Movilidad Urbana','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('97779712','0','3899392','1','Estacionamiento Regulado','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('82182145','1','3899392','1','Administración ectrónica','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4784129','1','3899392','1','Web Municipal','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('82182147','0','3899392','1','Tarjeta Ciudadana','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('97550336','0','3899392','1','Transporte Público','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('103677952','0','3899392','1','semaforos','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849665','0','3899392','1','Turismo','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5472256','1','3899392','1','Escuelas Infantiles','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('6029312','0','3899392','1','Archivo Municipal','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('9043968','0','3899392','1','Patrimonio Cultural','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('9043969','1','3899392','1','Bicicletas','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('97779713','0','3899392','1','Señalización','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849668','2','3899392','1','Participación Ciudadana','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849669','3','3899392','1','Infraestructuras:Conservacion','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849670','0','3899392','1','Buzón el Alcalde','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('4849671','0','3899392','1','Parques y Jardines','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144579','0','3899392','1','Instituto Mpal. Salud Publica','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144580','0','3899392','1','Zaragoza Cultural','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144581','0','3899392','1','Personas Mayores','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144582','0','3899392','1','Cementerio','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144583','1','3899392','1','Publicaciones y concursos','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144585','0','3899392','1','Bibliotecas Municipales','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144586','0','3899392','1','Estadística y Padrón','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('5144587','0','3899392','1','Urbanismo','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('16777217','1','3899392','1','Enseñanzas Artísticas','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('15564801','0','3899392','1','Jurídico Servicios Públicos','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('16777216','0','3899392','1','Zaragoza Internacional','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('82182144','0','3899392','1','Centro Documentación del Agua','1','N');
Insert into HBCATEGORYLEVELS (CAL_HBID,CAL_HBVERSION,CAL_PARENT,CAL_LEVEL,CAL_NAME,CAL_ISCATEGORY,AUTOASSIGN) values ('106954752','1','3899392','1','Calidad de contenidos','1','N');
REM INSERTING into HBCATEGORYSCALINGGROUPS
SET DEFINE OFF;
REM INSERTING into HBCOMPANIES
SET DEFINE OFF;
Insert into HBCOMPANIES (CPN_HBID,CPN_HBVERSION,CPN_NAME,CPN_OTHERS,CPN_PHONE,CPN_FAX,CPN_ADRESS,CPN_CITY,CPN_STATE,CPN_CP) values ('1','0','Empresa por defecto',' ',' ',' ',' ',' ',' ',' ');
REM INSERTING into HBCONFIGURATION
SET DEFINE OFF;
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('1','2','Servidor SMTP','192.168.168.44','HSMPT');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('2','0','Session de correo',' ','SMAIL');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('3','0','Directorio del Web Root',' ','WEBROOT');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('4','5','Directorio Ficheros Adjuntos','/home/ob544e/Documentos/cont/aplicaciones/ticketing/','LOADFILES');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('5','0','URL de los Ficheros Ajuntos',' ','URLFILES');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('6','6','Direcci¿n Email del Remitente','25232871@zaragoza.es','FROMADDRES');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('7','3','Username del Servidor SMTP','25232871','USERSMTP');
Insert into HBCONFIGURATION (CNF_HBID,CNF_HBVERSION,CNF_FUNCTIONNAME,CNF_VALUE,CNF_INTERNALNAME) values ('8','3','Password del Servidor SMTP','aqc5fJYhzyuj6jS1','PWDSMTP');
REM INSERTING into HBDEPARTMENTS
SET DEFINE OFF;
Insert into HBDEPARTMENTS (DEP_HBID,DEP_NAME,DEP_HBVERSION) values ('1','DEPARTAMENTO POR DEFECTO','0');
REM INSERTING into HBUSERS
SET DEFINE OFF;
Insert into HBUSERS (USR_HBID,USR_USERNAME,PASSWORD,USR_HBID_DEPARTMENT,PER_FIRSTNAME,PER_LASTNAME,PER_PHONE1,PER_PHONE2,PER_EXT,PER_MOVILE,CLI_PLACEMENT,CLI_EMAIL,CLI_COMPANY,CLI_TREATMENT,CLI_POSITION,USR_HBVERSION,USR_HBTYPEDISCRIMINATOR,IDCASD,USR_HBID_COMPANY,CLI_ID_ZONE,CLI_ID_CATEGORY,CLI_CATEGORY,CLI_OTHERS,PER_ADDRESS,PER_CITY,PER_COUNTRY,PER_ZIPCODE,PER_NIF) values ('3506176','anonymous','','1','Usuario','No registrado',' ',' ',' ',' ',' ','anonymous@anonymous.es',' ',' ',' ','1','CLIENT','0','1',null,'2','0',' ','NO MODIFICAR EL REGISTRO','NO MODIFICAR EL REGISTRO','NO MODIFICAR EL REGISTRO','NO MODIFIC','NO MODIFIC');
Insert into HBUSERS (USR_HBID,USR_USERNAME,PASSWORD,USR_HBID_DEPARTMENT,PER_FIRSTNAME,PER_LASTNAME,PER_PHONE1,PER_PHONE2,PER_EXT,PER_MOVILE,CLI_PLACEMENT,CLI_EMAIL,CLI_COMPANY,CLI_TREATMENT,CLI_POSITION,USR_HBVERSION,USR_HBTYPEDISCRIMINATOR,IDCASD,USR_HBID_COMPANY,CLI_ID_ZONE,CLI_ID_CATEGORY,CLI_CATEGORY,CLI_OTHERS,PER_ADDRESS,PER_CITY,PER_COUNTRY,PER_ZIPCODE,PER_NIF) values ('2','Ofiweb','{MD5}4QrcOUm6Wau+VuBX8g+IPg==','1','Oficina','Web Municipal','976 721278',' ',' ',' ',' ',' ',' ',' ',' ','7','SUPERVISOR','0','1',null,null,'0',' ',' ',' ',' ',' ',' ');
REM INSERTING into HB_ENTIDADESEXTERNAS
SET DEFINE OFF;
REM INSERTING into HBHEADERDESCRIPTIONS
SET DEFINE OFF;
REM INSERTING into HBHEADERFIELDS
SET DEFINE OFF;
REM INSERTING into HBINVOICEABLEACTIONITEMS
SET DEFINE OFF;
REM INSERTING into HBLISTINGCOLUMNDESCRIPTIONS
SET DEFINE OFF;
REM INSERTING into HBLISTINGDESCRIPTIONS
SET DEFINE OFF;
REM INSERTING into HBLISTINGFORMENUS
SET DEFINE OFF;
REM INSERTING into HBMACHINES
SET DEFINE OFF;
REM INSERTING into HBMAGAZINES
SET DEFINE OFF;
REM INSERTING into HBMENUS
SET DEFINE OFF;
REM INSERTING into HBPARAMETRIZATIONS
SET DEFINE OFF;
REM INSERTING into HBPROPERTIES
SET DEFINE OFF;
REM INSERTING into HBPROPERTYSETTYPES
SET DEFINE OFF;
REM INSERTING into HBREQUESTACTIONOPERATIONS
SET DEFINE OFF;
REM INSERTING into HBREQUESTACTIONOPERATIONTYPES
SET DEFINE OFF;
REM INSERTING into HBREQUESTACTIONTYPES
SET DEFINE OFF;
REM INSERTING into HBREQUESTLOADFILES
SET DEFINE OFF;
REM INSERTING into HBREQUESTNUMBER_UNIQUE_KEY
SET DEFINE OFF;
Insert into HBREQUESTNUMBER_UNIQUE_KEY (REQUESTNUMBERID) values ('4');
REM INSERTING into HBREQUESTORIGINS
SET DEFINE OFF;
REM INSERTING into HBREQUESTPARAMETRIZATIONS
SET DEFINE OFF;
REM INSERTING into HBREQUESTPRIORITIES
SET DEFINE OFF;
Insert into HBREQUESTPRIORITIES (RPT_HBID,RPT_NAME,RPT_PRIORITY,RPT_HBVERSION,RPT_DEFAULT) values ('2','Normal','2','0','1');
Insert into HBREQUESTPRIORITIES (RPT_HBID,RPT_NAME,RPT_PRIORITY,RPT_HBVERSION,RPT_DEFAULT) values ('3','Alta','1','0','0');
REM INSERTING into HBREQUESTSTATES
SET DEFINE OFF;
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('6','Solicitada información','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('10','Derivada a Interno','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('1','Pendiente','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('2','Cerrada','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('3','No Asignada','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('4','Resuelta','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('5','Borrada','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('7','Derivada a Externo','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('8','Rechazada','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('9','Archivada','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('11','Rechazada por externo','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('12','Ampliar informaci¿ externo','0');
Insert into HBREQUESTSTATES (RST_HBID,RST_NAME,RST_HBVERSION) values ('15','Finalizada por externo','0');
REM INSERTING into HBREQUESTSUBSTATES
SET DEFINE OFF;
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('6','Solicitada información','6','1','0','0','0','0');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('10','Derivada a Inspector','10','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('1','Pendiente','1','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('2','Cerrada','2','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('3','No Asignada','3','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('4','Resuelta','4','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('5','Borrada','5','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('7','Derivada a Externo','7','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('8','Rechazada','8','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('9','Archivada','9','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('11','Rechazada por externo','11','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('12','Ampliar informaci¿ externo','12','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('14','Pendiente por valorac¿','14','1','0','0','0',' ');
Insert into HBREQUESTSUBSTATES (RSS_HBID,RSS_NAME,RSS_ID_REQUESTSTATE,RSS_ISSTATE,RSS_SLA_STOP,RSS_HBVERSION,RSS_SENDMAIL,RSS_MAILTO) values ('15','Finalizada por externo','15','1','0','0','0','0');
REM INSERTING into HBREQUESTTOKEN
SET DEFINE OFF;
REM INSERTING into HBREQUESTTYPES
SET DEFINE OFF;
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('12812288','Agradecimiento','0','0','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('4587520','Informaci¿n','1','1','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('1','Queja','1','0','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('2','Sugerencia','1','0','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('241532928','Requerimiento','1','0','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('240418816','Aviso','1','0','0');
Insert into HBREQUESTTYPES (RTY_HBID,RTY_NAME,RTY_HBVERSION,RTY_DEFAULT,RTY_TICKER) values ('250544128','Solicitud Información Pública','1','0','0');
REM INSERTING into HBSCALINGGROUPS
SET DEFINE OFF;
Insert into HBSCALINGGROUPS (SGP_HBID,SGP_NAME,SGP_HBVERSION,SGP_EMAILGROUP,SGP_AUTONOTIFICATION) values ('1','Web Municipal','1','admin@admin.es','1');
REM INSERTING into HBSCALINGGROUPUSERS
SET DEFINE OFF;
REM INSERTING into HBSEARCHESPECIFICATIONS
SET DEFINE OFF;
REM INSERTING into HBSTOCKMANAGERS
SET DEFINE OFF;
REM INSERTING into HBSTOCKMOVEMENTS
SET DEFINE OFF;
REM INSERTING into HBSTOCKMOVEMENTTYPE
SET DEFINE OFF;
REM INSERTING into HBSTOCKS
SET DEFINE OFF;
REM INSERTING into HBSTOCKSZONES
SET DEFINE OFF;
REM INSERTING into HBUSERS_ORIGIN
SET DEFINE OFF;
REM INSERTING into HBUSERTZONES
SET DEFINE OFF;
REM INSERTING into HBZONES
SET DEFINE OFF;
REM INSERTING into HIBERNATE_UNIQUE_KEY
SET DEFINE OFF;
Insert into HIBERNATE_UNIQUE_KEY (NEXT_HI) values ('5790');
REM INSERTING into REPORT_UNIQUE_KEY
SET DEFINE OFF;
Insert into REPORT_UNIQUE_KEY (INTERNALREPORTID) values ('0');
REM INSERTING into RESPUESTASTIPO
SET DEFINE OFF;
REM INSERTING into RPTREQCOUNTPERCATEGORYLEVEL
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERDAY
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERDEPARTMENT
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERGROUP
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERHOUR
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERORIGIN
SET DEFINE OFF;
REM INSERTING into RPTREQUESTCOUNTPERTYPE
SET DEFINE OFF;
REM INSERTING into RPTREQUESTTIMEPERCATEGORYLEVEL
SET DEFINE OFF;
REM INSERTING into HBREQUESTS
SET DEFINE OFF;
Insert into HBREQUESTS (RQT_HBID,RQT_HBVERSION,USR_HBID_REQUESTER,USR_HBID_INTRODUCER,USR_HBID_MANAGER,RST_ID,ROG_HBID,RTY_HBID,RPT_HBID,SGP_HBID,CAT_HBID,RQT_INTRODUCTIONDATETIME,RQT_CREATIONDESCRIPTION,RQT_REQUESTDATETIME,RQT_REQUESTDATE,RQT_REQUESTNUMBER,RQT_EXPECTEDRESOLUTIONDATETIME,RQT_CLOSEDATETIME,RQT_CLOSEDATE,MAC_HBID_MACHINE,NUMREFCASD,IDCASD,RQT_REQUESTHOUR,RQT_RESOLVEDDATATIME,RQT_PARENT_ID,RQT_PUBLIC,RQT_VALIDATED,RQT_GEOLOCATION,RQT_GESTORDATE,RQT_EXTERNODATE,RQT_EXTERNOID,OPERADOR,SOLICITA_RESPUESTA,RQT_INSPECTORDATE,RQT_INSPECTORID,RQT_ZONAINSPECCIONID,INTERNAL_STATUS,NOTES,ID_CITA,TOKEN,USER_ID,ID_CAT_SIP) values ('2147438621','3','3506176','3506176',null,'4','3','250544128','3','1','2',to_date('17/10/18','DD/MM/RR'),'solictud de información pública///Solicitud de información pública///nombre prueba apellidos prueba///prueba@prueba.es//////',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'4',to_date('17/11/18','DD/MM/RR'),null,null,null,'0','0','10',to_date('17/10/18','DD/MM/RR'),null,'S','R',null,null,null,null,null,null,null,null,null,null,'DNI Solicitante:123456789A
Modalidad de respuesta:Soporte papel
',null,'5FDGWVXID5JRMNPP5GL3N5WZH8LX07TTJEP1LHAT',null,null);
Insert into HBREQUESTS (RQT_HBID,RQT_HBVERSION,USR_HBID_REQUESTER,USR_HBID_INTRODUCER,USR_HBID_MANAGER,RST_ID,ROG_HBID,RTY_HBID,RPT_HBID,SGP_HBID,CAT_HBID,RQT_INTRODUCTIONDATETIME,RQT_CREATIONDESCRIPTION,RQT_REQUESTDATETIME,RQT_REQUESTDATE,RQT_REQUESTNUMBER,RQT_EXPECTEDRESOLUTIONDATETIME,RQT_CLOSEDATETIME,RQT_CLOSEDATE,MAC_HBID_MACHINE,NUMREFCASD,IDCASD,RQT_REQUESTHOUR,RQT_RESOLVEDDATATIME,RQT_PARENT_ID,RQT_PUBLIC,RQT_VALIDATED,RQT_GEOLOCATION,RQT_GESTORDATE,RQT_EXTERNODATE,RQT_EXTERNOID,OPERADOR,SOLICITA_RESPUESTA,RQT_INSPECTORDATE,RQT_INSPECTORID,RQT_ZONAINSPECCIONID,INTERNAL_STATUS,NOTES,ID_CITA,TOKEN,USER_ID,ID_CAT_SIP) values ('2147438623','0','3506176','3506176',null,'1','3','1','2','1','24182784',to_date('17/10/18','DD/MM/RR'),'errores de accesibilidad///prueba accesibilidad///prueba padron ///prueba@zaragoza.es///976721278///',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'5',to_date('17/11/18','DD/MM/RR'),null,null,null,'0','0','10',null,null,'N','N',null,to_date('17/10/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null,null,'FA9K2VOMT2KE4O58D928EJUAC1CD0OVDA37W38BH','1988',null);
Insert into HBREQUESTS (RQT_HBID,RQT_HBVERSION,USR_HBID_REQUESTER,USR_HBID_INTRODUCER,USR_HBID_MANAGER,RST_ID,ROG_HBID,RTY_HBID,RPT_HBID,SGP_HBID,CAT_HBID,RQT_INTRODUCTIONDATETIME,RQT_CREATIONDESCRIPTION,RQT_REQUESTDATETIME,RQT_REQUESTDATE,RQT_REQUESTNUMBER,RQT_EXPECTEDRESOLUTIONDATETIME,RQT_CLOSEDATETIME,RQT_CLOSEDATE,MAC_HBID_MACHINE,NUMREFCASD,IDCASD,RQT_REQUESTHOUR,RQT_RESOLVEDDATATIME,RQT_PARENT_ID,RQT_PUBLIC,RQT_VALIDATED,RQT_GEOLOCATION,RQT_GESTORDATE,RQT_EXTERNODATE,RQT_EXTERNOID,OPERADOR,SOLICITA_RESPUESTA,RQT_INSPECTORDATE,RQT_INSPECTORID,RQT_ZONAINSPECCIONID,INTERNAL_STATUS,NOTES,ID_CITA,TOKEN,USER_ID,ID_CAT_SIP) values ('2147438622','0','3506176','3506176',null,'1','3','1','2','1','24182784',to_date('17/10/18','DD/MM/RR'),'errores de queja///prueba de queja///prueba queja ///prueba@zaragoza.es///976721278///',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'3',to_date('17/11/18','DD/MM/RR'),null,null,null,'0','0','10',null,null,'N','N',null,to_date('17/10/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null,null,'4L3K0IBRYWOIU95SCLY2JJ046SB7XHQIU5TE151B','1988',null);
REM INSERTING into HBREQUESTACTIONS
SET DEFINE OFF;
Insert into HBREQUESTACTIONS (RQA_HBID,RQA_HBVERSION,RQA_DESCRIPTION,RQA_CREATIONDATETIME,RQA_REQUESTACTIONDATETIME,RQA_ELAPSEDSECONDS,USR_HBID_AGENT,RQT_HBID_REQUEST,RAT_HBID_TYPE,RSS_HBID_SUBSTATE,RSS_SLA_STOP,OPERADOR) values ('2147437519','0','solictud de información pública',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'0','3506176','2147438621',null,'3','0',null);
Insert into HBREQUESTACTIONS (RQA_HBID,RQA_HBVERSION,RQA_DESCRIPTION,RQA_CREATIONDATETIME,RQA_REQUESTACTIONDATETIME,RQA_ELAPSEDSECONDS,USR_HBID_AGENT,RQT_HBID_REQUEST,RAT_HBID_TYPE,RSS_HBID_SUBSTATE,RSS_SLA_STOP,OPERADOR) values ('2147437518','1','resuelta',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'0','2','2147438621','1','1','0','admin');
Insert into HBREQUESTACTIONS (RQA_HBID,RQA_HBVERSION,RQA_DESCRIPTION,RQA_CREATIONDATETIME,RQA_REQUESTACTIONDATETIME,RQA_ELAPSEDSECONDS,USR_HBID_AGENT,RQT_HBID_REQUEST,RAT_HBID_TYPE,RSS_HBID_SUBSTATE,RSS_SLA_STOP,OPERADOR) values ('2147437517','0','Cambio de Estado a Resuelta',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'0','2','2147438621',null,'4','0','admin');
Insert into HBREQUESTACTIONS (RQA_HBID,RQA_HBVERSION,RQA_DESCRIPTION,RQA_CREATIONDATETIME,RQA_REQUESTACTIONDATETIME,RQA_ELAPSEDSECONDS,USR_HBID_AGENT,RQT_HBID_REQUEST,RAT_HBID_TYPE,RSS_HBID_SUBSTATE,RSS_SLA_STOP,OPERADOR) values ('2147437521','0','errores de accesibilidad',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'0','3506176','2147438623',null,'3','0',null);
Insert into HBREQUESTACTIONS (RQA_HBID,RQA_HBVERSION,RQA_DESCRIPTION,RQA_CREATIONDATETIME,RQA_REQUESTACTIONDATETIME,RQA_ELAPSEDSECONDS,USR_HBID_AGENT,RQT_HBID_REQUEST,RAT_HBID_TYPE,RSS_HBID_SUBSTATE,RSS_SLA_STOP,OPERADOR) values ('2147437520','0','errores de accesibilidad',to_date('17/10/18','DD/MM/RR'),to_date('17/10/18','DD/MM/RR'),'0','3506176','2147438622',null,'3','0',null);
